// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TerroscapeApp.Database;
using TerroscapeApp.Models;

#nullable disable

namespace TerroscapeApp.Migrations
{
    [DbContext(typeof(TerroscapeStatsContext))]
    [Migration("20250114170500_OtherEnums")]
    partial class OtherEnums
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "game_name_enum", new[] { "base", "feral_instincts", "amorphous_peril", "lethal_immortals", "putrefied_enmity" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "killer_win_enum", new[] { "murder", "time", "other" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "survivor_state_enum", new[] { "alive", "injured", "dead" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "survivor_win_enum", new[] { "escape", "police", "plan", "other" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TerroscapeApp.Database.Avatar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstSkill")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("first_skill");

                    b.Property<DBEnums.GameNameEnum>("GameName")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("game_name_enum")
                        .HasDefaultValue(DBEnums.GameNameEnum.Base)
                        .HasColumnName("game_name");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("name");

                    b.Property<string>("SecondSkill")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("second_skill");

                    b.HasKey("Id")
                        .HasName("survivor_pkey");

                    b.ToTable("avatar", (string)null);
                });

            modelBuilder.Entity("TerroscapeApp.Database.Killer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<DBEnums.GameNameEnum>("GameName")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("game_name_enum")
                        .HasDefaultValue(DBEnums.GameNameEnum.Base)
                        .HasColumnName("game_name");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("name");

                    b.Property<int>("Strength")
                        .HasColumnType("integer")
                        .HasColumnName("strength");

                    b.HasKey("Id")
                        .HasName("killer_id_pk");

                    b.ToTable("killer", (string)null);
                });

            modelBuilder.Entity("TerroscapeApp.Database.Map", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<int>("LocationsNum")
                        .HasColumnType("integer")
                        .HasColumnName("locations_num");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("map_id_pk");

                    b.HasIndex(new[] { "Name" }, "map_name_uq")
                        .IsUnique();

                    b.ToTable("map", (string)null);
                });

            modelBuilder.Entity("TerroscapeApp.Database.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("login");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("player_id_pk");

                    b.HasIndex(new[] { "Login" }, "player_login_uq")
                        .IsUnique();

                    b.ToTable("player", (string)null);
                });

            modelBuilder.Entity("TerroscapeApp.Database.Round", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<bool?>("DonePlan")
                        .HasColumnType("boolean")
                        .HasColumnName("done_plan");

                    b.Property<bool>("DoneRadio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("done_radio");

                    b.Property<int>("FirstSurvivor")
                        .HasColumnType("integer")
                        .HasColumnName("first_survivor");

                    b.Property<bool>("GotKeys")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("got_keys");

                    b.Property<bool>("HasPlans")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("has_plans");

                    b.Property<DBEnums.KillerWinEnum?>("HowKillerWin")
                        .HasColumnType("killer_win_enum")
                        .HasColumnName("how_killer_win");

                    b.Property<DBEnums.SurvivorWinEnum?>("HowSurvivorsWin")
                        .HasColumnType("survivor_win_enum")
                        .HasColumnName("how_survivors_win");

                    b.Property<int>("KillerBoostNum")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("killer_boost_num");

                    b.Property<int>("KillerId")
                        .HasColumnType("integer")
                        .HasColumnName("killer_id");

                    b.Property<int>("KillerLevel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("killer_level");

                    b.Property<int>("KillerPlayerId")
                        .HasColumnType("integer")
                        .HasColumnName("killer_player_id");

                    b.Property<bool>("KillerWin")
                        .HasColumnType("boolean")
                        .HasColumnName("killer_win");

                    b.Property<int>("MapId")
                        .HasColumnType("integer")
                        .HasColumnName("map_id");

                    b.Property<int>("SecondSurvivor")
                        .HasColumnType("integer")
                        .HasColumnName("second_survivor");

                    b.Property<int>("SurvivorBoostNum")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("survivor_boost_num");

                    b.Property<int>("ThirdSurvivor")
                        .HasColumnType("integer")
                        .HasColumnName("third_survivor");

                    b.HasKey("Id")
                        .HasName("round_id_pk");

                    b.HasIndex("FirstSurvivor");

                    b.HasIndex("KillerId");

                    b.HasIndex("KillerPlayerId");

                    b.HasIndex("MapId");

                    b.HasIndex("SecondSurvivor");

                    b.HasIndex("ThirdSurvivor");

                    b.ToTable("round", (string)null);
                });

            modelBuilder.Entity("TerroscapeApp.Database.Survivor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<int>("AvatarId")
                        .HasColumnType("integer")
                        .HasColumnName("avatar_id");

                    b.Property<int?>("PlayerId")
                        .HasColumnType("integer")
                        .HasColumnName("player_id");

                    b.Property<DBEnums.SurvivorStateEnum>("State")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("survivor_state_enum")
                        .HasDefaultValue(DBEnums.SurvivorStateEnum.Alive)
                        .HasColumnName("state");

                    b.HasKey("Id")
                        .HasName("survivor_id_pk");

                    b.HasIndex("AvatarId");

                    b.HasIndex("PlayerId");

                    b.ToTable("survivor", (string)null);
                });

            modelBuilder.Entity("TerroscapeApp.Database.Round", b =>
                {
                    b.HasOne("TerroscapeApp.Database.Survivor", "FirstSurvivorNavigation")
                        .WithMany("RoundFirstSurvivorNavigations")
                        .HasForeignKey("FirstSurvivor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("round_first_survivor_fk");

                    b.HasOne("TerroscapeApp.Database.Killer", "Killer")
                        .WithMany("Rounds")
                        .HasForeignKey("KillerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("round_killer_fk");

                    b.HasOne("TerroscapeApp.Database.Player", "KillerPlayer")
                        .WithMany("Rounds")
                        .HasForeignKey("KillerPlayerId")
                        .IsRequired()
                        .HasConstraintName("round_killer_player_fk");

                    b.HasOne("TerroscapeApp.Database.Map", "Map")
                        .WithMany("Rounds")
                        .HasForeignKey("MapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("round_map_fk");

                    b.HasOne("TerroscapeApp.Database.Survivor", "SecondSurvivorNavigation")
                        .WithMany("RoundSecondSurvivorNavigations")
                        .HasForeignKey("SecondSurvivor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("round_second_survivor_fk");

                    b.HasOne("TerroscapeApp.Database.Survivor", "ThirdSurvivorNavigation")
                        .WithMany("RoundThirdSurvivorNavigations")
                        .HasForeignKey("ThirdSurvivor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("round_third_survivor_fk");

                    b.Navigation("FirstSurvivorNavigation");

                    b.Navigation("Killer");

                    b.Navigation("KillerPlayer");

                    b.Navigation("Map");

                    b.Navigation("SecondSurvivorNavigation");

                    b.Navigation("ThirdSurvivorNavigation");
                });

            modelBuilder.Entity("TerroscapeApp.Database.Survivor", b =>
                {
                    b.HasOne("TerroscapeApp.Database.Avatar", "Avatar")
                        .WithMany("Survivors")
                        .HasForeignKey("AvatarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("survivor_avatar_fk");

                    b.HasOne("TerroscapeApp.Database.Player", "Player")
                        .WithMany("Survivors")
                        .HasForeignKey("PlayerId")
                        .HasConstraintName("survivor_player_fk");

                    b.Navigation("Avatar");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("TerroscapeApp.Database.Avatar", b =>
                {
                    b.Navigation("Survivors");
                });

            modelBuilder.Entity("TerroscapeApp.Database.Killer", b =>
                {
                    b.Navigation("Rounds");
                });

            modelBuilder.Entity("TerroscapeApp.Database.Map", b =>
                {
                    b.Navigation("Rounds");
                });

            modelBuilder.Entity("TerroscapeApp.Database.Player", b =>
                {
                    b.Navigation("Rounds");

                    b.Navigation("Survivors");
                });

            modelBuilder.Entity("TerroscapeApp.Database.Survivor", b =>
                {
                    b.Navigation("RoundFirstSurvivorNavigations");

                    b.Navigation("RoundSecondSurvivorNavigations");

                    b.Navigation("RoundThirdSurvivorNavigations");
                });
#pragma warning restore 612, 618
        }
    }
}
